# ~/.config/starship.toml

add_newline = true


format = """$conda$directory$git_branch$git_status$python$nodejs$character"""

[character]
# success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
# success_symbol = '[:]( green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
success_symbol = ''

[hostname]
ssh_only = true
format = 'on [$hostname](bold yellow) '
disabled = false

[directory]
home_symbol = '~'
read_only_style = '197'
read_only = ''

[python]
python_binary = ['venv']
symbol = 'ğŸ '

# ~/.config/starship.toml

[conda]
disabled = false
ignore_base = false
format = '\([$environment](dimmed green)\) '
